---
- name: Install ElasticSearch.
  apt:
    name: elasticsearch
    state: latest
  notify:
    - reload systemd
    - restart elasticsearch

- name: Configure ElasticSearch.
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: 'cluster\.name:'
      line: 'cluster.name: {{ elk_cluster_name }}'
    - regexp: 'network\.host:'
      line: 'network.host: "localhost"'
  notify:
    - restart elasticsearch

- name: Start elasticsearch service.
  service:
    name: elasticsearch
    state: started
    enabled: yes
  register: elasticsearch_service_start_result

  # Wait a bit for the service to start if it wasn't running.
- name: Wait for elasticsearch service to start.
  pause:
    seconds: 20
  when: elasticsearch_service_start_result.changed
