---
# tasks file for role-elk
- include: packages.yml
  tags: packages

- include: elasticsearch.yml
  tags: elasticsearch

- include: logstash.yml
  tags: logstash

- include: kibana.yml
  tags: kibana

- include: nginx.yml
  tags: nginx

- include: ufw.yml
  when: elk_configure_firewall == true
  tags: ufw
