---
- name: Install ufw.
  become: yes
  apt:
    name: ufw
    state: installed

- name: Allow SSH access to logserver.
  ufw:
    rule: allow
    proto: tcp
    from_ip: any
    port: 22
  notify: restart ufw

- name: Allow access to Kibana web interface from anywhere.
  ufw:
    rule: allow
    proto: tcp
    from_ip: any
    port: "{{ item }}"
  notify: restart ufw
  with_items:
    - 80
    - 443

- name: Start ufw service.
  service:
    name: ufw
    state: running
    enabled: yes

- name: Enable ufw functionality.
  ufw:
    state: enabled
